---
- name: Demo Minishift, Weave Scope and Istio.
  hosts: Pisc0
  connection: local
  gather_facts: yes
  vars:
    hostname_and_profile: openshift1

  roles:
    - role: chilcano.minishift
      minishift:
        action_to_trigger: install # [ install | fresh_install | clean ]
        action:
          clean:
            installation: true
            local_repo: false
            local_tmp: false
            dependencies: false
          install: true
          start: true
        post_copy_oc: false
        start_options:
          vm-driver: virtualbox
          iso-url: file:///Users/Chilcano/Downloads/__kube_repo/minishift-b2d-iso/v1.2.0/minishift-b2d.iso
          #iso-url: https://github.com/minishift/minishift-b2d-iso/releases/download/v1.2.0/minishift-b2d.iso
          profile: "{{ hostname_and_profile }}"
          openshift-version: "v3.7.0"
        openshift:
          admin_usr: "system:admin"
          admin_pwd: anypassword
        repo:
          name: minishift/minishift
          release_tag_name: "v1.11.0"

    - role: chilcano.weave-scope
      weave_scope:
        minishift:
          profile: "{{ hostname_and_profile }}"
        openshift:
          admin_usr: "system:admin"
          admin_pwd: anypassword
          hostname: "{{ hostname_and_profile }}"
        #repo: https://cloud.weave.works/k8s/scope.yaml   ## default
        repo: /Users/Chilcano/Downloads/__kube_repo/weave-scope/scope.yaml
        action_to_trigger: deploy  # [ deploy | clean ]

    - role: chilcano.istio
      istio:
        action_to_trigger: deploy  # [ deploy | clean ]
        action:
          deploy:
            istioctl: true    # istioctl
            core: true        # core components
            addons: true      # prometheus, graphana, zipkin, servicegraph
            sample_apps: true # bookinfo
          clean: true
        minishift:
          profile: "{{ hostname_and_profile }}"
        openshift:
          project: istio-system
          hostname: "{{ hostname_and_profile }}"
          admin_usr: "system:admin"
          admin_pwd: anypassword
          istio_usr: developer
          istio_pwd: anypassword
        repo:
          name: istio/istio
          release_tag_name: "0.2.7"
