---
- name: Remove Minishift VM.
  hosts: Pisc0
  connection: local
  gather_facts: yes
  vars:
    vm: openshift1

  roles:
    #- role: chilcano.minishift
    - role: ../ansible-role-minishift
      minishift:
        action_to_trigger: clean # [ install | fresh_install | clean ]
        action:
          clean:
            installation: true
            local_repo: false
            local_tmp: false
            dependencies: false
        start_options:
          profile: "{{ vm }}"
        openshift:
          admin_usr: "system:admin"
          admin_pwd: anypassword
