- name: post | Check if 'oc' binary exists
  stat:
    path: "{{ __ms.dir.local_bin }}/oc"
  register: oc_client

- name: post | Get the path to the 'oc' client for Minishift '{{ __ms.start_options.profile }}' instance
  find:
    paths: "{{ lookup('env', 'HOME') }}/.minishift/profiles/{{ __ms.start_options.profile }}/cache/oc"
    patterns: "v*"
    hidden: yes
    file_type: directory
  register: oc_versions

- name: post | Set latest_oc_version
  set_fact:
    latest_oc_version: "{{ oc_versions.files | last }}"

- name: post | Copy '{{ latest_oc_version }}' client
  copy:
    src: "{{ latest_oc_version.path }}/oc"
    dest: "{{ __ms.dir.local_bin }}/oc"
    mode: 0755
    remote_src: yes
  become: yes
  become_user: root
