# Script which fixes issue with Minishift VM's IP.
# It works with Docker Machine.
# Based on:
#   https://github.com/ahilbig/docker-machine-ipconfig.git
#   https://github.com/ahilbig/docker-machine-ipconfig/blob/master/minishift-ipconfig
#   https://github.com/ahilbig/docker-machine-ipconfig/blob/master/docker-machine-ipconfig
#
# minishift profile set openshift01         -> set VM as 'active'
# minishift-ipconfig ls                     -> it lists the current IP status
# minishift-ipconfig static                 -> it uses the DHCP-assigned IP
# minishift profile set openshift02         -> set VM as 'active'
# minishift-ipconfig static 192.168.99.102  -> it uses a specified IP
# minishift-ipconfig dhcp                   -> it does DHCP assigns (restores initial behaviour) a dynamic IP
#

- name: set_ip_b2d | Copy 'minishift-ipconfig-b2d' script to '{{ __ms.dir.local_bin }}'
  template:
    src: minishift-ipconfig-b2d.j2.sh
    dest: "{{ __ms.dir.local_bin }}/minishift-ipconfig-b2d.sh"
    mode: 0755
    remote_src: yes
  become: yes
