- name: stop | debug '__ms.start_options.profile'
  debug:
    var: __ms.start_options.profile

- name: stop | debug 'instance_status'
  debug:
    var: instance_status

- name: stop | debug 'instance_ip_address'
  debug:
    var: instance_ip_address

- name: stop | Get all Minishift profiles
  command: "minishift profiles list"
  register: minishift_profiles_stop

- name: stop | Set the 'profile {{ __ms.start_options.profile }} / IP {{ instance_ip_address }}' Minishift instance as 'active'
  command: "minishift profile set {{ __ms.start_options.profile }}"
  when: minishift_profiles_stop.stdout | regex_search(minishift_profile_regex)

- name: stop | Stop Minishift profile '{{ __ms.start_options.profile }}'
  command: "minishift stop"
  when: minishift_profiles_stop.stdout | regex_search(minishift_profile_regex)
