#- name: stop | Get Minishift '{{ __ms.start_options.profile }}' status
#  command: "minishift --profile {{ __ms.start_options.profile }} status"
#  register: minishift_profile_stop_stat
#  ignore_errors: yes

- name: stop | Get all Minishift profiles
  command: "minishift profiles list"
  register: minishift_profiles_stop

- name: stop | Defining the Minishift profile's regex
  set_fact:
    minishift_profile_regex: "- {{ __ms.start_options.profile }}(.+)"

- name: stop | Set the '{{ __ms.start_options.profile }}' Minishift profile as 'active'
  command: "minishift profile set {{ __ms.start_options.profile }}"
  when: minishift_profiles_stop.stdout | regex_search(minishift_profile_regex)

- name: stop | Stop Minishift profile '{{ __ms.start_options.profile }}'
  command: "minishift stop"
  when: minishift_profiles_stop.stdout | regex_search(minishift_profile_regex)
