
##### install app:
# oc apply -f <(istioctl kube-inject -f istio/samples/apps/bookinfo/bookinfo.yaml)
# oc expose svc servicegrap

- name: deploy_sample_apps | Set facts
  set_fact:
     _istio_repo_: "{{ __i.dir.local_repo }}/{{ istio_asset_name_without_ext }}"

- name: deploy_sample_apps | Deploy BookInfo App with 'istioctl'
  shell: "{{ item }}"
  with_items:
    - "oc apply -f <( istioctl kube-inject -f istio-{{ __i.repo.release_tag_name }}/samples/apps/bookinfo/bookinfo.yaml )"
    - "oc expose svc servicegraph"
  args:
    executable: "/bin/bash"
    chdir: "{{ _istio_repo_ }}"

##### Test Service Mesh / Using Grafana Pod (or another Pod):
#  export GRAFANA_POD=$(oc get pods -l app=grafana -o jsonpath={.items[0].metadata.name})
#  oc exec $GRAFANA_POD -- curl -o /dev/null -s -w "%{http_code}\n" http://istio-ingress/productpage
#  open http://$(oc get routes servicegraph -o jsonpath={.spec.host})/dotviz
#
