
apiVersion: v1
kind: Route
metadata:
  name: "{{ __ms.openshift.route_docker_registry.name }}"
spec:
  host: "{{ __ms.start_options['public-hostname'] }}"
  to:
    kind: Service
    name: docker-registry
    weight: 100
  port:
    targetPort: 5000-tcp
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Allow
status:
  ingress:
    -
      host: "{{ __ms.start_options['public-hostname'] }}"
      routerName: router
      conditions:
        -
          type: Admitted
          status: 'True'
